using System;
using System.Collections.Generic;
using UnityEngine;

namespace ProjectEri.SkillSystemV2
{
    public interface ISpellMotionBlocker
    {
        bool BlocksSpellMotion { get; }
    }

    public enum SpatialForceDirection
    {
        TowardCenter,
        AwayFromCenter
    }

    public enum SpatialForceCenter
    {
        DeliveryCenter,
        Caster,
        ImpactPoint,
        AimedPoint
    }

    public enum SpatialForceFalloff
    {
        None,
        Linear,
        Inverse
    }

    [Serializable]
    public sealed class SpatialForceEffectSettings : SpellEffectSettings
    {
        [Tooltip("Pull targets toward the center or push them away from it.")]
        [SerializeField] private SpatialForceDirection direction =
            SpatialForceDirection.TowardCenter;

        [Tooltip("The point that acts as the force center. Delivery Center is recommended for lingering areas and moving spell objects.")]
        [SerializeField] private SpatialForceCenter center =
            SpatialForceCenter.DeliveryCenter;

        [Tooltip("Movement speed generated by the force in world units per second.")]
        [SerializeField, Min(0f)] private float strength = 5f;

        [Tooltip("Maximum speed this force can produce after combining overlapping sources.")]
        [SerializeField, Min(0f)] private float maximumSpeed = 8f;

        [Tooltip("How force strength changes with distance from its center.")]
        [SerializeField] private SpatialForceFalloff falloff =
            SpatialForceFalloff.None;

        [Tooltip("Distance used for falloff. Zero automatically uses the delivery's interaction radius when available.")]
        [SerializeField, Min(0f)] private float falloffDistance;

        [Tooltip("Targets this close to the center stop moving instead of oscillating across it.")]
        [SerializeField, Min(0f)] private float stopDistance = 0.12f;

        [Tooltip("Duration for a non-area force application. Area forces remain active exactly while the target is inside.")]
        [SerializeField, Min(0.02f)] private float duration = 0.25f;

        [Tooltip("Prevent forced movement from passing through selected obstacle layers.")]
        [SerializeField] private bool respectObstacles = true;

        [Tooltip("World layers that block forced movement when Respect Obstacles is enabled.")]
        [SerializeField] private LayerMask obstacleMask;

        public SpatialForceDirection Direction => direction;
        public SpatialForceCenter Center => center;
        public float Strength => Mathf.Max(0f, strength);
        public float MaximumSpeed => Mathf.Max(0f, maximumSpeed);
        public SpatialForceFalloff Falloff => falloff;
        public float FalloffDistance => Mathf.Max(0f, falloffDistance);
        public float StopDistance => Mathf.Max(0f, stopDistance);
        public float Duration => Mathf.Max(0.02f, duration);
        public bool RespectObstacles => respectObstacles;
        public LayerMask ObstacleMask => obstacleMask;

        public SpatialForceEffectSettings() { }

        public SpatialForceEffectSettings(
            SpatialForceDirection forceDirection,
            SpatialForceCenter forceCenter,
            float forceStrength,
            float maxSpeed,
            float forceDuration,
            float stoppingDistance = 0.12f,
            SpatialForceFalloff forceFalloff = SpatialForceFalloff.None,
            float falloffRange = 0f,
            bool blockByObstacles = true,
            LayerMask blockers = default)
        {
            direction = forceDirection;
            center = forceCenter;
            strength = Mathf.Max(0f, forceStrength);
            maximumSpeed = Mathf.Max(0f, maxSpeed);
            duration = Mathf.Max(0.02f, forceDuration);
            stopDistance = Mathf.Max(0f, stoppingDistance);
            falloff = forceFalloff;
            falloffDistance = Mathf.Max(0f, falloffRange);
            respectObstacles = blockByObstacles;
            obstacleMask = blockers;
        }
    }

    public abstract class SpatialForceEffectDefinitionBase :
        EffectDefinition,
        IAreaPresenceEffectDefinition
    {
        [Tooltip("Default pull or push direction.")]
        [SerializeField] private SpatialForceDirection direction =
            SpatialForceDirection.TowardCenter;
        [Tooltip("Default force-center source.")]
        [SerializeField] private SpatialForceCenter center =
            SpatialForceCenter.DeliveryCenter;
        [Tooltip("Default forced movement speed.")]
        [SerializeField, Min(0f)] private float strength = 5f;
        [Tooltip("Default maximum combined force speed.")]
        [SerializeField, Min(0f)] private float maximumSpeed = 8f;
        [Tooltip("Default distance falloff behavior.")]
        [SerializeField] private SpatialForceFalloff falloff =
            SpatialForceFalloff.None;
        [Tooltip("Default explicit falloff range. Zero infers it from the delivery.")]
        [SerializeField, Min(0f)] private float falloffDistance;
        [Tooltip("Default center dead zone.")]
        [SerializeField, Min(0f)] private float stopDistance = 0.12f;
        [Tooltip("Default duration outside persistent areas.")]
        [SerializeField, Min(0.02f)] private float duration = 0.25f;
        [Tooltip("Default obstacle-respecting behavior.")]
        [SerializeField] private bool respectObstacles = true;
        [Tooltip("Default force obstruction layers.")]
        [SerializeField] private LayerMask obstacleMask;

        public override Type SettingsType =>
            typeof(SpatialForceEffectSettings);

        public override SpellEffectSettings CreateDefaultSettings()
        {
            return new SpatialForceEffectSettings(
                direction,
                center,
                strength,
                maximumSpeed,
                duration,
                stopDistance,
                falloff,
                falloffDistance,
                respectObstacles,
                obstacleMask);
        }

        public override bool Apply(in SpellEffectContext context)
        {
            return Apply(context, CreateDefaultSettings());
        }

        public override bool Apply(
            in SpellEffectContext context,
            SpellEffectSettings settings)
        {
            SpatialForceEffectSettings resolved = Resolve(settings);
            SpellActorMotionController2D controller =
                SpellActorMotionUtility.GetOrAddController(context.Target);
            if (controller == null || resolved.Strength <= 0f)
                return false;

            ResolveCenter(
                context,
                resolved,
                out Transform centerTransform,
                out Vector2 centerPoint,
                out float inferredRadius);
            UnityEngine.Object source = context.DeliveryRuntime != null
                ? context.DeliveryRuntime
                : this;
            controller.ApplyTimedForce(
                source,
                BuildKey(context, resolved),
                centerTransform,
                centerPoint,
                inferredRadius,
                resolved,
                context.Spell != null &&
                context.Spell.Timing.TimeMode == SpellTimeMode.Unscaled);
            return true;
        }

        public bool ApplyPresence(
            in SpellEffectContext context,
            Component source,
            SpellEffectSettings settings)
        {
            if (source == null)
                return false;

            SpatialForceEffectSettings resolved = Resolve(settings);
            SpellActorMotionController2D controller =
                SpellActorMotionUtility.GetOrAddController(context.Target);
            if (controller == null || resolved.Strength <= 0f)
                return false;

            ResolveCenter(
                context,
                resolved,
                out Transform centerTransform,
                out Vector2 centerPoint,
                out float inferredRadius);
            controller.SetPersistentForce(
                source,
                BuildPresenceKey(source, resolved),
                centerTransform,
                centerPoint,
                inferredRadius,
                resolved);
            return true;
        }

        public void RemovePresence(
            GameObject target,
            Component source,
            SpellEffectSettings settings)
        {
            SpellActorMotionController2D controller =
                SpellActorMotionUtility.FindController(target);
            if (controller == null || source == null)
                return;

            controller.RemoveForce(
                source,
                BuildPresenceKey(source, Resolve(settings)));
        }

        public override string DescribeApplicationFailure(
            in SpellEffectContext context,
            SpellEffectSettings settings)
        {
            if (context.Target == null)
                return "Spatial Force needs an actor target.";
            if (SpellActorMotionUtility.FindBody(context.Target) == null)
                return "Spatial Force needs a Rigidbody2D on the target actor.";
            return "Spatial Force has zero strength or could not resolve its center.";
        }

        public override void CollectValidationIssues(
            List<SpellValidationIssue> issues,
            SpellEffectSettings settings)
        {
            if (issues == null)
                return;
            SpatialForceEffectSettings resolved = Resolve(settings);
            if (resolved.Strength <= 0f)
            {
                issues.Add(new SpellValidationIssue(
                    SpellValidationSeverity.Warning,
                    "Spatial Force has zero Strength and will not move targets."));
            }
            if (resolved.RespectObstacles &&
                resolved.ObstacleMask.value == 0)
            {
                issues.Add(new SpellValidationIssue(
                    SpellValidationSeverity.Warning,
                    "Spatial Force respects obstacles, but its Obstacle Mask is Nothing."));
            }
        }

        private SpatialForceEffectSettings Resolve(
            SpellEffectSettings settings)
        {
            return settings as SpatialForceEffectSettings ??
                   (SpatialForceEffectSettings)CreateDefaultSettings();
        }

        private static void ResolveCenter(
            in SpellEffectContext context,
            SpatialForceEffectSettings settings,
            out Transform centerTransform,
            out Vector2 centerPoint,
            out float inferredRadius)
        {
            centerTransform = null;
            inferredRadius = 0f;
            switch (settings.Center)
            {
                case SpatialForceCenter.Caster:
                    centerTransform = context.Cast.Caster != null
                        ? context.Cast.Caster.transform
                        : null;
                    centerPoint = centerTransform != null
                        ? (Vector2)centerTransform.position
                        : context.Cast.Origin;
                    break;
                case SpatialForceCenter.AimedPoint:
                    centerPoint = context.Cast.HasTargetPoint
                        ? context.Cast.TargetPoint
                        : context.HitPoint;
                    break;
                case SpatialForceCenter.ImpactPoint:
                    centerPoint = context.HitPoint;
                    break;
                default:
                    centerTransform = context.DeliveryRuntime != null
                        ? context.DeliveryRuntime.transform
                        : null;
                    centerPoint = centerTransform != null
                        ? (Vector2)centerTransform.position
                        : context.HitPoint;
                    if (context.DeliveryRuntime is
                        ISpellDeliveryInteractionVolume volume)
                    {
                        inferredRadius = volume.InteractionRadius;
                    }
                    break;
            }
        }

        private string BuildKey(
            in SpellEffectContext context,
            SpatialForceEffectSettings settings)
        {
            return $"{GetInstanceID()}:{(int)settings.Center}:{context.Cast.RootCastId}";
        }

        private string BuildPresenceKey(
            Component source,
            SpatialForceEffectSettings settings)
        {
            return $"{GetInstanceID()}:{(int)settings.Center}:{source.GetInstanceID()}";
        }
    }

    public enum ActorRelocationMode
    {
        Travel,
        InstantTeleport
    }

    public enum ActorRelocationDestination
    {
        AimedPoint,
        EventPoint,
        DeliveryCenter,
        Caster,
        SelectedTarget
    }

    [Serializable]
    public sealed class ActorRelocationEffectSettings : SpellEffectSettings
    {
        [Tooltip("Travel visibly over time or teleport immediately.")]
        [SerializeField] private ActorRelocationMode mode =
            ActorRelocationMode.Travel;
        [Tooltip("Where the affected actor is moved.")]
        [SerializeField] private ActorRelocationDestination destination =
            ActorRelocationDestination.AimedPoint;
        [Tooltip("Travel speed in world units per second. Ignored by an instant teleport.")]
        [SerializeField, Min(0.01f)] private float speed = 10f;
        [Tooltip("Maximum distance the effect may move the target.")]
        [SerializeField, Min(0.01f)] private float maximumDistance = 8f;
        [Tooltip("Additional world-space offset added to the resolved destination.")]
        [SerializeField] private Vector2 destinationOffset;
        [Tooltip("Require an unobstructed path to the destination.")]
        [SerializeField] private bool requireLineOfSight = true;
        [Tooltip("Layers that block travel or teleportation.")]
        [SerializeField] private LayerMask obstacleMask;
        [Tooltip("Stop at the last safe point instead of rejecting a destination behind an obstacle.")]
        [SerializeField] private bool clampToObstacles = true;
        [Tooltip("Extra clearance kept between the actor and blocking geometry.")]
        [SerializeField, Min(0f)] private float obstacleSkin = 0.03f;
        [Tooltip("Keep the target's existing Rigidbody2D velocity after an instant teleport.")]
        [SerializeField] private bool preserveVelocity;

        public ActorRelocationMode Mode => mode;
        public ActorRelocationDestination Destination => destination;
        public float Speed => Mathf.Max(0.01f, speed);
        public float MaximumDistance => Mathf.Max(0.01f, maximumDistance);
        public Vector2 DestinationOffset => destinationOffset;
        public bool RequireLineOfSight => requireLineOfSight;
        public LayerMask ObstacleMask => obstacleMask;
        public bool ClampToObstacles => clampToObstacles;
        public float ObstacleSkin => Mathf.Max(0f, obstacleSkin);
        public bool PreserveVelocity => preserveVelocity;

        public ActorRelocationEffectSettings() { }

        public ActorRelocationEffectSettings(
            ActorRelocationMode relocationMode,
            ActorRelocationDestination destinationSource,
            float travelSpeed,
            float maxDistance,
            bool lineOfSight = true,
            LayerMask blockers = default,
            bool clampAtBlocker = true,
            bool keepVelocity = false,
            Vector2 offset = default,
            float skin = 0.03f)
        {
            mode = relocationMode;
            destination = destinationSource;
            speed = Mathf.Max(0.01f, travelSpeed);
            maximumDistance = Mathf.Max(0.01f, maxDistance);
            requireLineOfSight = lineOfSight;
            obstacleMask = blockers;
            clampToObstacles = clampAtBlocker;
            preserveVelocity = keepVelocity;
            destinationOffset = offset;
            obstacleSkin = Mathf.Max(0f, skin);
        }
    }

    public abstract class ActorRelocationEffectDefinitionBase : EffectDefinition
    {
        [Tooltip("Default choice between visible travel and an immediate teleport.")]
        [SerializeField] private ActorRelocationMode mode =
            ActorRelocationMode.Travel;
        [Tooltip("Default source used to resolve the affected actor's destination.")]
        [SerializeField] private ActorRelocationDestination destination =
            ActorRelocationDestination.AimedPoint;
        [Tooltip("Default travel speed copied into each spell. Ignored for an instant teleport.")]
        [SerializeField, Min(0.01f)] private float speed = 10f;
        [Tooltip("Default maximum distance the effect may move an actor.")]
        [SerializeField, Min(0.01f)] private float maximumDistance = 8f;
        [Tooltip("Default world-space offset added to the resolved destination.")]
        [SerializeField] private Vector2 destinationOffset;
        [Tooltip("Default choice for whether obstacles must leave a clear path to the destination.")]
        [SerializeField] private bool requireLineOfSight = true;
        [Tooltip("Default Unity layers that block actor relocation.")]
        [SerializeField] private LayerMask obstacleMask;
        [Tooltip("Default choice to stop at the last safe point instead of rejecting a blocked relocation.")]
        [SerializeField] private bool clampToObstacles = true;
        [Tooltip("Default clearance kept between the relocated actor and blocking geometry.")]
        [SerializeField, Min(0f)] private float obstacleSkin = 0.03f;
        [Tooltip("Default choice for retaining Rigidbody2D velocity after an instant teleport.")]
        [SerializeField] private bool preserveVelocity;

        public override Type SettingsType =>
            typeof(ActorRelocationEffectSettings);

        public override SpellEffectSettings CreateDefaultSettings()
        {
            var settings = new ActorRelocationEffectSettings(
                mode,
                destination,
                speed,
                maximumDistance,
                requireLineOfSight,
                obstacleMask,
                clampToObstacles,
                preserveVelocity,
                destinationOffset,
                obstacleSkin);
            return settings;
        }

        public override bool Apply(in SpellEffectContext context)
        {
            return Apply(context, CreateDefaultSettings());
        }

        public override bool Apply(
            in SpellEffectContext context,
            SpellEffectSettings settings)
        {
            ActorRelocationEffectSettings resolved = Resolve(settings);
            SpellActorMotionController2D controller =
                SpellActorMotionUtility.GetOrAddController(context.Target);
            if (controller == null ||
                !TryResolveDestination(context, resolved, out Vector2 point))
            {
                return false;
            }

            return controller.Relocate(point, resolved);
        }

        public override string DescribeApplicationFailure(
            in SpellEffectContext context,
            SpellEffectSettings settings)
        {
            if (context.Target == null)
                return "Relocate Actor needs an actor target.";
            if (SpellActorMotionUtility.FindBody(context.Target) == null)
                return "Relocate Actor needs a Rigidbody2D on the affected actor.";
            return "The requested destination was missing, blocked, or already occupied by the actor.";
        }

        public override void CollectValidationIssues(
            List<SpellValidationIssue> issues,
            SpellEffectSettings settings)
        {
            if (issues == null)
                return;
            ActorRelocationEffectSettings resolved = Resolve(settings);
            if (resolved.RequireLineOfSight &&
                resolved.ObstacleMask.value == 0)
            {
                issues.Add(new SpellValidationIssue(
                    SpellValidationSeverity.Warning,
                    "Relocate Actor requires line of sight, but its Obstacle Mask is Nothing."));
            }
        }

        private ActorRelocationEffectSettings Resolve(
            SpellEffectSettings settings)
        {
            return settings as ActorRelocationEffectSettings ??
                   (ActorRelocationEffectSettings)CreateDefaultSettings();
        }

        private static bool TryResolveDestination(
            in SpellEffectContext context,
            ActorRelocationEffectSettings settings,
            out Vector2 point)
        {
            switch (settings.Destination)
            {
                case ActorRelocationDestination.Caster:
                    if (context.Cast.Caster == null)
                    {
                        point = default;
                        return false;
                    }
                    point = context.Cast.Caster.transform.position;
                    break;
                case ActorRelocationDestination.SelectedTarget:
                    if (context.Cast.SelectedTarget == null)
                    {
                        point = default;
                        return false;
                    }
                    point = context.Cast.SelectedTarget.transform.position;
                    break;
                case ActorRelocationDestination.DeliveryCenter:
                    if (context.DeliveryRuntime == null)
                    {
                        point = default;
                        return false;
                    }
                    point = context.DeliveryRuntime.transform.position;
                    break;
                case ActorRelocationDestination.EventPoint:
                    if (!context.HasDeliveryEvent)
                    {
                        point = default;
                        return false;
                    }
                    point = context.HitPoint;
                    break;
                default:
                    if (!context.Cast.HasTargetPoint)
                    {
                        point = default;
                        return false;
                    }
                    point = context.Cast.TargetPoint;
                    break;
            }

            point += settings.DestinationOffset;
            return true;
        }

    }

    [DefaultExecutionOrder(-50)]
    [DisallowMultipleComponent]
    [RequireComponent(typeof(Rigidbody2D))]
    public sealed class SpellActorMotionController2D : MonoBehaviour
    {
        private sealed class ForceEntry
        {
            public UnityEngine.Object Source;
            public int SourceId;
            public string Key;
            public Transform CenterTransform;
            public Vector2 CenterPoint;
            public float InferredRadius;
            public SpatialForceEffectSettings Settings;
            public float ExpiresAt;
            public bool Persistent;
            public bool Unscaled;
        }

        [SerializeField] private Rigidbody2D body;
        [SerializeField] private bool debugMotionActive;
        [SerializeField] private Vector2 debugForcedVelocity;
        [SerializeField] private string debugMode = "Idle";

        private readonly List<ForceEntry> forces = new List<ForceEntry>();
        private readonly RaycastHit2D[] castBuffer = new RaycastHit2D[12];
        private MonoBehaviour[] motionBlockerBehaviours;
        private bool relocating;
        private Vector2 relocationDestination;
        private ActorRelocationEffectSettings relocationSettings;

        public bool IsControllingMotion
        {
            get
            {
                PruneForces();
                return relocating || forces.Count > 0;
            }
        }

        public Vector2 ForcedVelocity => debugForcedVelocity;

        private void Awake()
        {
            if (body == null)
                body = GetComponent<Rigidbody2D>();
            motionBlockerBehaviours = GetComponents<MonoBehaviour>();
        }

        public void ApplyTimedForce(
            UnityEngine.Object source,
            string key,
            Transform centerTransform,
            Vector2 centerPoint,
            float inferredRadius,
            SpatialForceEffectSettings settings,
            bool useUnscaledTime = false)
        {
            SetForce(
                source,
                key,
                centerTransform,
                centerPoint,
                inferredRadius,
                settings,
                persistent: false,
                useUnscaledTime: useUnscaledTime);
        }

        public void SetPersistentForce(
            UnityEngine.Object source,
            string key,
            Transform centerTransform,
            Vector2 centerPoint,
            float inferredRadius,
            SpatialForceEffectSettings settings)
        {
            SetForce(
                source,
                key,
                centerTransform,
                centerPoint,
                inferredRadius,
                settings,
                persistent: true,
                useUnscaledTime: false);
        }

        public void RemoveForce(UnityEngine.Object source, string key)
        {
            if (source == null)
                return;

            int sourceId = source.GetInstanceID();
            for (int i = forces.Count - 1; i >= 0; i--)
            {
                if (forces[i].SourceId == sourceId && forces[i].Key == key)
                    forces.RemoveAt(i);
            }
        }

        public bool Relocate(
            Vector2 requestedDestination,
            ActorRelocationEffectSettings settings)
        {
            if (body == null)
                body = GetComponent<Rigidbody2D>();
            if (body == null || body.bodyType == RigidbodyType2D.Static ||
                settings == null)
            {
                return false;
            }

            Vector2 origin = body.position;
            Vector2 offset = requestedDestination - origin;
            float distance = offset.magnitude;
            if (distance <= 0.0001f)
                return false;

            Vector2 destination = origin +
                offset.normalized * Mathf.Min(distance, settings.MaximumDistance);
            if (!ResolveObstacleLimitedDestination(
                    origin,
                    destination,
                    settings.RequireLineOfSight,
                    settings.ObstacleMask,
                    settings.ObstacleSkin,
                    settings.ClampToObstacles,
                    out destination))
            {
                return false;
            }

            if (settings.Mode == ActorRelocationMode.InstantTeleport)
            {
                body.position = destination;
                transform.position = destination;
                if (!settings.PreserveVelocity)
                    body.linearVelocity = Vector2.zero;
                relocating = false;
                debugMode = "Teleported";
                return true;
            }

            relocationDestination = destination;
            relocationSettings = settings;
            relocating = true;
            debugMode = "Relocating";
            return true;
        }

        private void FixedUpdate()
        {
            PruneForces();
            if (body == null || body.bodyType == RigidbodyType2D.Static)
                return;

            if (IsBlockedByAnotherMotionOwner())
            {
                debugMotionActive = true;
                debugForcedVelocity = Vector2.zero;
                debugMode = "Waiting for higher-priority motion";
                return;
            }

            if (relocating)
            {
                TickRelocation();
                return;
            }

            if (forces.Count == 0)
            {
                debugMotionActive = false;
                debugForcedVelocity = Vector2.zero;
                if (debugMode != "Teleported")
                    debugMode = "Idle";
                return;
            }

            Vector2 velocity = ResolveCombinedForce();
            debugMotionActive = true;
            debugForcedVelocity = velocity;
            debugMode = "Spatial Force";
            MoveByVelocity(velocity, ResolveCombinedObstacleMask());
        }

        private void TickRelocation()
        {
            Vector2 offset = relocationDestination - body.position;
            float distance = offset.magnitude;
            float step = relocationSettings.Speed * Time.fixedDeltaTime;
            if (distance <= Mathf.Max(0.01f, step))
            {
                body.MovePosition(relocationDestination);
                body.linearVelocity = Vector2.zero;
                relocating = false;
                debugForcedVelocity = Vector2.zero;
                debugMotionActive = false;
                debugMode = "Relocation Complete";
                return;
            }

            Vector2 velocity = offset.normalized * relocationSettings.Speed;
            debugMotionActive = true;
            debugForcedVelocity = velocity;
            MoveByVelocity(
                velocity,
                relocationSettings.RequireLineOfSight
                    ? relocationSettings.ObstacleMask
                    : 0);
        }

        private void MoveByVelocity(Vector2 velocity, LayerMask obstacleMask)
        {
            float distance = velocity.magnitude * Time.fixedDeltaTime;
            if (distance <= 0f)
                return;

            Vector2 direction = velocity.normalized;
            float allowed = GetAllowedDistance(
                direction,
                distance,
                obstacleMask,
                0.03f);
            body.MovePosition(body.position + direction * allowed);
        }

        private Vector2 ResolveCombinedForce()
        {
            Vector2 total = Vector2.zero;
            float maximumSpeed = float.PositiveInfinity;
            Vector2 position = body.position;

            for (int i = 0; i < forces.Count; i++)
            {
                ForceEntry entry = forces[i];
                Vector2 center = entry.CenterTransform != null
                    ? (Vector2)entry.CenterTransform.position
                    : entry.CenterPoint;
                Vector2 offset = center - position;
                float distance = offset.magnitude;
                if (distance <= entry.Settings.StopDistance)
                    continue;

                float factor = ResolveFalloff(entry, distance);
                Vector2 direction = offset.normalized;
                if (entry.Settings.Direction ==
                    SpatialForceDirection.AwayFromCenter)
                {
                    direction = -direction;
                }

                float dealt = SpellStatModifierUtility.Evaluate(
                    ResolveSourceCaster(entry),
                    SpellActorStat.KnockbackDealt,
                    1f);
                float received = SpellStatModifierUtility.Evaluate(
                    gameObject,
                    SpellActorStat.KnockbackReceived,
                    1f);
                total += direction * entry.Settings.Strength * factor *
                         dealt * received;
                if (entry.Settings.MaximumSpeed > 0f)
                {
                    maximumSpeed = Mathf.Min(
                        maximumSpeed,
                        entry.Settings.MaximumSpeed);
                }
            }

            if (!float.IsPositiveInfinity(maximumSpeed) &&
                total.magnitude > maximumSpeed)
            {
                total = total.normalized * maximumSpeed;
            }
            return total;
        }

        private static GameObject ResolveSourceCaster(ForceEntry entry)
        {
            Component component = entry.Source as Component;
            if (component is ISpellDeliveryInteractionVolume volume)
                return volume.InteractionExecutionContext.Cast.Caster;
            return component != null ? component.gameObject : null;
        }

        private static float ResolveFalloff(ForceEntry entry, float distance)
        {
            float range = entry.Settings.FalloffDistance > 0f
                ? entry.Settings.FalloffDistance
                : entry.InferredRadius;
            if (entry.Settings.Falloff == SpatialForceFalloff.None ||
                range <= 0.0001f)
            {
                return 1f;
            }

            float normalized = Mathf.Clamp01(distance / range);
            return entry.Settings.Falloff == SpatialForceFalloff.Linear
                ? 1f - normalized
                : 1f / Mathf.Max(1f, distance);
        }

        private LayerMask ResolveCombinedObstacleMask()
        {
            int mask = 0;
            for (int i = 0; i < forces.Count; i++)
            {
                if (forces[i].Settings.RespectObstacles)
                    mask |= forces[i].Settings.ObstacleMask.value;
            }
            return mask;
        }

        private void SetForce(
            UnityEngine.Object source,
            string key,
            Transform centerTransform,
            Vector2 centerPoint,
            float inferredRadius,
            SpatialForceEffectSettings settings,
            bool persistent,
            bool useUnscaledTime)
        {
            if (source == null || settings == null)
                return;

            int sourceId = source.GetInstanceID();
            ForceEntry entry = null;
            for (int i = 0; i < forces.Count; i++)
            {
                if (forces[i].SourceId == sourceId && forces[i].Key == key)
                {
                    entry = forces[i];
                    break;
                }
            }

            if (entry == null)
            {
                entry = new ForceEntry();
                forces.Add(entry);
            }

            entry.Source = source;
            entry.SourceId = sourceId;
            entry.Key = key;
            entry.CenterTransform = centerTransform;
            entry.CenterPoint = centerPoint;
            entry.InferredRadius = inferredRadius;
            entry.Settings = settings;
            entry.Persistent = persistent;
            entry.Unscaled = useUnscaledTime;
            entry.ExpiresAt = persistent
                ? float.PositiveInfinity
                : CurrentTime(useUnscaledTime) + settings.Duration;
        }

        private void PruneForces()
        {
            for (int i = forces.Count - 1; i >= 0; i--)
            {
                ForceEntry entry = forces[i];
                if (entry.Source == null ||
                    (!entry.Persistent && entry.ExpiresAt <=
                     CurrentTime(entry.Unscaled)))
                {
                    forces.RemoveAt(i);
                }
            }
        }

        private static float CurrentTime(bool unscaled)
        {
            return unscaled ? Time.unscaledTime : Time.time;
        }

        private bool IsBlockedByAnotherMotionOwner()
        {
            if (motionBlockerBehaviours == null)
                motionBlockerBehaviours = GetComponents<MonoBehaviour>();

            for (int i = 0; i < motionBlockerBehaviours.Length; i++)
            {
                if (motionBlockerBehaviours[i] is ISpellMotionBlocker blocker &&
                    blocker.BlocksSpellMotion)
                {
                    return true;
                }
            }
            return false;
        }

        private bool ResolveObstacleLimitedDestination(
            Vector2 origin,
            Vector2 requested,
            bool useObstacles,
            LayerMask obstacleMask,
            float skin,
            bool clamp,
            out Vector2 resolved)
        {
            resolved = requested;
            Vector2 offset = requested - origin;
            float distance = offset.magnitude;
            if (!useObstacles || obstacleMask.value == 0 || distance <= 0f)
                return true;

            float allowed = GetAllowedDistance(
                offset.normalized,
                distance,
                obstacleMask,
                skin);
            if (allowed >= distance - 0.0001f)
                return true;
            if (!clamp || allowed <= 0.001f)
                return false;

            resolved = origin + offset.normalized * allowed;
            return true;
        }

        private float GetAllowedDistance(
            Vector2 direction,
            float distance,
            LayerMask obstacleMask,
            float skin)
        {
            if (body == null || obstacleMask.value == 0)
                return distance;

            var filter = new ContactFilter2D();
            filter.SetLayerMask(obstacleMask);
            filter.useTriggers = false;
            int count = body.Cast(
                direction,
                filter,
                castBuffer,
                distance + Mathf.Max(0f, skin));
            float allowed = distance;
            for (int i = 0; i < count; i++)
            {
                if (castBuffer[i].collider == null)
                    continue;
                allowed = Mathf.Min(
                    allowed,
                    Mathf.Max(0f, castBuffer[i].distance - skin));
            }
            return allowed;
        }
    }

    public static class SpellActorMotionUtility
    {
        public static Rigidbody2D FindBody(GameObject actor)
        {
            if (actor == null)
                return null;
            GameObject resolved = SpellTargetResolver.Resolve(actor) ?? actor;
            return resolved.GetComponent<Rigidbody2D>() ??
                   resolved.GetComponentInParent<Rigidbody2D>();
        }

        public static SpellActorMotionController2D FindController(
            GameObject actor)
        {
            Rigidbody2D body = FindBody(actor);
            return body != null
                ? body.GetComponent<SpellActorMotionController2D>()
                : null;
        }

        public static SpellActorMotionController2D GetOrAddController(
            GameObject actor)
        {
            Rigidbody2D body = FindBody(actor);
            if (body == null || body.bodyType == RigidbodyType2D.Static)
                return null;
            SpellActorMotionController2D controller =
                body.GetComponent<SpellActorMotionController2D>();
            return controller != null
                ? controller
                : body.gameObject.AddComponent<
                    SpellActorMotionController2D>();
        }
    }
}
